version: '3'

services:
  waziup-system:
    image: python:latest
    volumes:
      - ./waziup-system/system:/app
      - /var/run/dbus:/var/run/dbus
      - /etc/hostapd:/etc/hostapd
      - /sbin/shutdown:/sbin/shutdown
      - /sys/class/gpio:/sys/class/gpio
      - /dev/mem:/dev/mem
    ports:
      - "5000:5000"
    privileged: true
    network_mode:
      "host"
    environment:
      - FLASK_DEBUG=1
      - FLASK_PORT=5000
#    command: sh -c "python /app/setup.py; python /app/api.py"
    command: sh -c "python /app/setup.py; python /app/api.py | python /app/start.py"
    # Infinite loop, to keep it alive, for debugging
#    #command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"

  webui:
    image: php:7.2-apache
    volumes:
      - ./waziup-system/webui:/var/www/html/
    ports:
      - "80:80"
    network_mode: "host"
    logging:
      driver: none
    depends_on:
      - waziup-system
  
  waziup-edge:
    build: ./waziup-edge
    image: waziup/waziup-edge
    ports:
      - "880:80"
      - "1883:1883"
    environment:
      - HTTP_PORT=80
    network_mode: host
    restart: always

  mongo:
    image: mongo:3.2.8
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/local --quiet
      interval: 5s
      timeout: 5s
      retries: 12
    extra_hosts:
      - "localhost:127.0.0.1"
