version: '3'
services:

#-------------------------#

  wazigate-system:
    build: ./wazigate-system
    volumes:
      - ./wazigate-system:/go/src/wazigate-system

#-------------------------#

  wazigate-ui:
    build: ./wazigate-ui
    environment:
      - DEBUG_MODE=0


#-------------------------#

  wazigate-edge:
    build: ./wazigate-edge

#-------------------------#

  wazigate-mongo:
    build: ./wazigate-mongo

#-------------------------#

  wazigate-lora:
    build: ./wazigate-lora

#-------------------------#