version: '3'

services:
  waziup-system:
    build: ./waziup-system
    image: waziup/waziup-system
    ports:
      - "80:80"
    environment:
      - HTTP_PORT=80
      - CLOUD_WAZIUP=http://localhost:800/api
    network_mode: host
    restart: always
  
  waziup-edge:
    build: ./waziup-edge
    image: waziup/waziup-edge
    ports:
      - "800:800"
    environment:
      - HTTP_PORT=80
    network_mode: host
    restart: always

  mongo:
    image: mongo:3.2.8
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/local --quiet
      interval: 5s
      timeout: 5s
      retries: 12
    extra_hosts:
      - "localhost:127.0.0.1"
