version: '3'
services:

#-------------------------#
  
  wazigate-edge:
    container_name: wazigate-edge
    image: waziup/wazigate-edge:dev
    build: ./wazigate-edge
    ports:
      - "80:80"
      - "1883:1883"
    volumes:
      - ./wazigate-edge:/root/conf
      - ./apps:/root/apps # Where the WaziApps are installed
      - /var/run:/var/run # Mapping the host sockets
      - ./wazigate-edge:/go/src/github.com/Waziup/wazigate-edge/
      - ./setup/resolv.conf:/etc/resolv.conf
    environment:
      - WAZIUP_HTTP_ADDR=:80
#      - WAZIUP_HTTPS_ADDR=:4443
#      - WAZIUP_MQTT_ADDR=:1883
#      - WAZIUP_MQTTS_ADDR=:8883
#      - WAZIUP_TLS_CRT =             TLS Cert File (.crt)
#      - WAZIUP_TLS_KEY =             TLS Key File (.key)
      - WAZIUP_MONGO=localhost:27017
      - WAZIUP_CLOUDS_FILE=/root/conf/clouds.json
      #- WAZIGATE_HOST_ADDR=/var/run/wazigate-host.sock
    network_mode: host
    depends_on:
      - wazigate-mongo
    healthcheck:
      test: curl --fail http://localhost:880/device || exit 1 
      interval: 30s
      retries: 10 # Will try for 5 minutes
    restart: always

#-------------------------#

  wazigate-mongo:
    container_name: wazigate-mongo
    image: waziup/wazigate-mongo:V1.1-Beta1
    build: ./wazigate-mongo
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./wazigate-mongo/data:/data
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/local --quiet
      interval: 5s
      timeout: 5s
      retries: 12
    extra_hosts:
      - "localhost:127.0.0.1"
    network_mode: host                 # has to be fixed later to be accessed only locally
    restart: always
#    entrypoint: "mongod --journal"

<<<<<<< HEAD
#-------------------------#
=======
#-------------------------#
  
  wazigate-edge:
    container_name: wazigate-edge
    image: waziup/wazigate-edge:v1.2
    build:
      context: ./wazigate-edge
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "880:880"
      - "1883:1883"
    volumes:
      - ./wazigate-edge:/root/conf
      - ./apps:/root/apps
    #  - ./setup/resolv.conf:/etc/resolv.conf
    environment:
      - WAZIUP_HTTP_ADDR=:880
  #      - WAZIUP_HTTPS_ADDR=:4443
  #      - WAZIUP_MQTT_ADDR=:1883
  #      - WAZIUP_MQTTS_ADDR=:8883
  #      - WAZIUP_TLS_CRT =             TLS Cert File (.crt)
  #      - WAZIUP_TLS_KEY =             TLS Key File (.key)
      - WAZIUP_MONGO=wazigate-mongo:27017
      - WAZIUP_CLOUDS_FILE=/root/conf/clouds.json
    depends_on:
      - wazigate-mongo
    healthcheck:
      test: curl --fail http://127.0.0.1:880/device || exit 1 
      interval: 30s
      retries: 10 # Will try for 5 minutes
    restart: always

#-------------------------#

networks:
  default:
    external:
      name: wazigate
>>>>>>> branch 'master' of https://github.com/Waziup/WaziGate
